name: FaaS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build function
      uses: LucasRoesler/openfaas-action/build@v0.1.0
      with:
        tag: "latest"
        path: "api.yml"

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: ramiro/faas-api
        tag_with_ref: true
        tag_with_sha: true
