name: FaaS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      
    - name: Build function
      uses: rberrelleza/openfaas-action/build@db4ea7e36ee49ccce7a88a884d308e205d6d60b1
      with:
        tag: "latest"
        path: "api.yml"

    - name: Push function
      uses: rberrelleza/openfaas-action/push@db4ea7e36ee49ccce7a88a884d308e205d6d60b1
      with:
        tag: "latest"
        path: "api.yml"
