name: FaaS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build function
      uses: rberrelleza/openfaas-action/build@87d9efe48f358542b05b3bf0ede5e020ede2d8a4
      with:
        tag: "latest"
        path: "api.yml"

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      
    - name: Push function
      uses: rberrelleza/openfaas-action/push@87d9efe48f358542b05b3bf0ede5e020ede2d8a4
      with:
        tag: "latest"
        path: "api.yml"
