name: FaaS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build function
      uses: rberrelleza/openfaas-action/build@9eec30ce4fefab6977e8875fc99490b4454cf992
      with:
        tag: "latest"
        path: "api.yml"

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      
    - name: Push function
      uses: rberrelleza/openfaas-action/push@9eec30ce4fefab6977e8875fc99490b4454cf992
      with:
        tag: "latest"
        path: "api.yml"
